In [17]:

import pandas as pd
import numpy as np
import cv2
import os

dlsrc = r'\\kukissd\Kyu_Sync\Research\Active\Aging_organized\svs\svs_back_deeplab\classification_for_DL_skin_v6_control'
feather_src = r'\\kukissd\Kyu_Sync\Research\Active\Aging_organized\svs\roi_annotation'
feathers = [_ for _ in os.listdir(feather_src) if _.endswith('feather')]

dfs =[]
for idxf,feather in enumerate(feathers):

    try:
        img = cv2.imread(os.path.join(dlsrc,feather.replace('feather','tif')),cv2.IMREAD_GRAYSCALE)
        df = pd.read_feather(os.path.join(feather_src,feather))
        df = df[df['classname']=='tissue']
        df = df.reset_index(drop=True)
    except:
        continue
    if img is None:
        continue
    rsf = 4.192313429125


    for index, row in df.iterrows():
        x = row['x']/rsf
        x = x.astype('int')
        y = row['y']/rsf
        y = y.astype('int')
        c = np.column_stack((x,y))

        mask = np.zeros_like(img)

        try:
            cv2.drawContours(mask, [c], -1, 255, -1)
        except:
            print(idxf)
            print(c)

        out = np.zeros_like(img)
        out[mask == 255] = img[mask == 255]

        comp,b1=np.histogram(out,bins=range(1,12))
        comp = comp[0:9]
        comp = comp/np.sum(comp)
        df2 = pd.DataFrame({'imagename':feather,'age':int(feather[2:4]),'gender':feather[1],'sectionid':index,'composition':[comp],'compsum':np.sum(comp)})
        dfs.append(df2)

dfcomp = pd.concat(dfs)
dfcomp = dfcomp.reset_index(drop=True)
dfcomp.to_feather('comp.feather')

In [18]:
dfcomp

imagename  age gender  sectionid  \
0    wf16_b2_01.feather   16      f          0   
1    wf16_b2_01.feather   16      f          1   
2    wf16_b2_01.feather   16      f          2   
3    wf16_b2_01.feather   16      f          3   
4    wf16_b2_01.feather   16      f          4   
..                  ...  ...    ...        ...   
247  wm71_b4_01.feather   71      m          3   
248  wm84_b4_01.feather   84      m          0   
249  wm84_b4_01.feather   84      m          1   
250  wm84_b4_01.feather   84      m          2   
251  wm84_b4_01.feather   84      m          3   

                                           composition  compsum  
0    [0.00857751107497916, 0.023671063017380888, 0....      1.0  
1    [0.013106016579411992, 0.022917304029196017, 0...      1.0  
2    [0.01009851346389726, 0.0015357238622236307, 0...      1.0  
3    [0.024021112925813302, 0.027647532601960595, 0...      1.0  
4    [0.024321810275928658, 0.03334618914846616, 0....      1.0  
..                                                 ...      ...  
247  [0.010177486889118348, 0.015761281223230828, 0...      1.0  
248  [0.02913824907837251, 0.04885251713301508, 0.0...      1.0  
249  [0.04937448015619761, 0.03623551653150833, 0.0...      1.0  
250  [0.025591329465092124, 0.05871840573144079, 0....      1.0  
251  [0.03435031098231086, 0.04037825544456621, 0.0...      1.0  

[252 rows x 6 columns]

In [63]:
np.set_printoptions(precision=1,suppress=True)
df1 = dfcomp[(0<dfcomp['age']) & (dfcomp['age']<21)]
np.mean(df1['composition'])*100
# corn = []
# for idxf, rowf in df1.iterrows():
#     corn.append(rowf['composition'][1])
# corn

array([ 1.9,  3.3,  0.5,  1.7,  0.6,  0.9,  2.9, 85.8,  2.4])

In [64]:
df1 = dfcomp[(20<dfcomp['age']) & (dfcomp['age']<41)]
np.mean(df1['composition'])*100
# corn = []
# for idxf, rowf in df1.iterrows():
#     corn.append(rowf['composition'][1])
# corn

array([ 1.9,  2.8,  0.6,  1.6,  0.9,  0.9,  2.9, 84.2,  4.1])

In [65]:
df1 = dfcomp[(40<dfcomp['age']) & (dfcomp['age']<61)]
np.mean(df1['composition'])*100
# corn = []
# for idxf, rowf in df1.iterrows():
#     corn.append(rowf['composition'][1])
# corn

array([ 1.3,  2.4,  0.6,  1.3,  0.9,  1.4,  2.4, 85.1,  4.6])

In [66]:
df1 = dfcomp[(60<dfcomp['age']) & (dfcomp['age']<81)]
np.mean(df1['composition'])*100
# corn = []
# for idxf, rowf in df1.iterrows():
#     corn.append(rowf['composition'][1])
# corn

array([ 1.3,  1.7,  0.5,  1.4,  0.6,  1. ,  2.3, 84.4,  6.8])

In [67]:
df1 = dfcomp[(80<dfcomp['age']) & (dfcomp['age']<101)]
np.mean(df1['composition'])*100
# corn = []
# for idxf, rowf in df1.iterrows():
#     corn.append(rowf['composition'][1])
# corn

array([ 2.5,  2.3,  0.4,  2.5,  1. ,  1.2,  2.6, 79.1,  8.5])

In [49]:
# corn = []
# for idxf, rowf in df1.iterrows():
#     corn.append(rowf['composition'][1])
# corn

[0.029689042904039134,
 0.020088714646916465,
 0.01935655698800831,
 0.021998453701305327,
 0.015171677714992116,
 0.028487924803584582,
 0.03104127413138127,
 0.019395828701077072,
 0.017792528109378588,
 0.04047732577107436,
 0.03937542937363721,
 0.020120907258980924,
 0.007279652491793635,
 0.018685961419378797,
 0.026291543116437707,
 0.02939973790742641,
 0.047237493207095485,
 0.029893349175078705,
 0.013972349990858965,
 0.01593867656114805,
 0.04489838532061172,
 0.012955345469871466,
 0.041208713520578616,
 0.016178963065279016,
 0.012823695886775918,
 0.01160189909120774,
 0.02828238540429124,
 0.016140540627735338,
 0.02913824907837251,
 0.04937448015619761,
 0.025591329465092124,
 0.03435031098231086]